# Generated by Django 4.1.3 on 2022-11-23 12:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Job_catagories',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('catagory_name', models.CharField(max_length=2001)),
                ('group_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.joined_groups')),
            ],
        ),
    ]
