# Generated by Django 4.1.3 on 2022-11-23 13:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_job_catagories'),
    ]

    operations = [
        migrations.RenameField(
            model_name='job_catagories',
            old_name='group_name',
            new_name='group',
        ),
    ]
