# Generated by Django 4.1.3 on 2022-11-28 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_jobs'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobs',
            name='job_name',
            field=models.CharField(max_length=200),
        ),
    ]
