# Generated by Django 4.1.3 on 2022-11-28 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_alter_jobs_job_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobs',
            name='job_url',
            field=models.CharField(max_length=200),
        ),
    ]
