# Generated by Django 4.1.3 on 2022-11-28 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_alter_jobs_job_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobs',
            name='job_url',
            field=models.URLField(),
        ),
    ]
