# Generated by Django 4.1.3 on 2022-11-28 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_alter_jobs_job_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobs',
            name='job_description',
            field=models.TextField(default=''),
        ),
    ]
