# Generated by Django 4.1.3 on 2022-11-28 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_jobs_job_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='job_catagories',
            name='catagory_filtering_words',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='job_catagories',
            name='catagory_name',
            field=models.CharField(max_length=200),
        ),
    ]
