# Generated by Django 4.1.3 on 2022-11-28 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_job_catagories_catagory_filtering_words_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobs',
            name='job_date',
            field=models.DateField(auto_now=True),
        ),
    ]
