# Generated by Django 4.1.3 on 2022-11-28 16:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_alter_jobs_job_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='jobs',
            old_name='catagory',
            new_name='catagory_id',
        ),
    ]
