# Generated by Django 4.1.3 on 2022-11-30 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_alter_job_catagories_catagory_filtering_words'),
    ]

    operations = [
        migrations.RenameField(
            model_name='jobs',
            old_name='job_description',
            new_name='job_description_en',
        ),
        migrations.AddField(
            model_name='jobs',
            name='job_description_original',
            field=models.TextField(default=''),
        ),
    ]
