# Generated by Django 4.1.3 on 2022-12-01 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_remove_jobs_job_description_en_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobs',
            name='company_name',
            field=models.TextField(default=''),
        ),
    ]
