# Generated by Django 4.1.3 on 2022-12-01 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0015_jobs_company_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobs',
            name='company_name',
            field=models.CharField(default='', max_length=200),
        ),
    ]
