# Generated by Django 4.1.3 on 2022-12-01 12:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0016_alter_jobs_company_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Joined_Channels',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('channel_name', models.CharField(max_length=200)),
                ('channel_id', models.CharField(max_length=200)),
            ],
        ),
        migrations.AlterField(
            model_name='job_catagories',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.joined_channels'),
        ),
        migrations.DeleteModel(
            name='Joined_Groups',
        ),
    ]
