# Generated by Django 4.1.3 on 2022-12-01 12:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0017_joined_channels_alter_job_catagories_group_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='job_catagories',
            old_name='group',
            new_name='channel',
        ),
    ]
