# Generated by Django 4.1.3 on 2022-12-01 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0018_rename_group_job_catagories_channel'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobs',
            name='posted',
            field=models.BooleanField(default=False),
        ),
    ]
